experiment: MLMNegMixed
name: MLM / Mixed Experiment
seed: 42
data_collator: DataCollatorForLanguageModeling
model:
  name: prajjwal1/bert-small
  freeze_lower: 0
  freeze_upper: 3
  target_path: ./models/
  tmp_path: ./models/
training:
  epochs: 3
  batch_size: 20
  lr: 5e-5
  eval_steps_n: 10000
  eval_steps: True
data:
  path: ./data/processed/mlm_mixed/data.txt
  path_orig: ./data/processed/roberta_filtered/negation_aware_data.txt
  path_synth: ./data/processed/wn_neg_processed/data_wn_unmasked.txt
  mp_activate: False
  test-prop: 0.05
  val-prop: 0.5
  blocksize: 128
  amount: 1
  fingerprint: 1234567

debug: False
