experiment: MLMExperiment - LARGE
name: Neg Only Experiment - LARGE
seed: 42
model:
  name: roberta-large
  freeze_lower: 0
  freeze_upper: 16
  target_path: ./models/
  tmp_path: ./models/
training:
        epochs: 5
  batch_size: 16
  lr: 5e-5
data:
  path: './data/processed/data.txt'
  test-prop: 0.05
  blocksize: 128
