preprocessing:
  wiki:
    wiki_proportion: 0.1
    target: ../data/interim/wiki/
  owt:
    proportion: 0.1
    target: ../data/interim/owt/
  cc_news:
    proportion: 0.1
    target: ../data/interim/cc_news/
  bc:
    proportion: 0.1
    target: ../data/interim/bc/
  tmp:
    tmp_folder: ../data/interim/tmp/
    rolling_window: 2
    keys_list:
      - wiki
      - owt
      - cc_news
      - bc
  final:
    data_path: ../data/processed/negation_aware_data.txt
