preprocessing:
  wiki:
    wiki_proportion: 1
    target: ../data/interim/wiki_large/
  owt:
    proportion: 1
    target: ../data/interim/owt_large/
  cc_news:
    proportion: 1
    target: ../data/interim/cc_news_large/
  bc:
    proportion: 1
    target: ../data/interim/bc_large/
  tmp:
    tmp_folder: ../data/interim/tmp_large/
    rolling_window: 2
    keys_list:
      - wiki
      - owt
      - cc_news
      - bc
  final:
    data_path: ../data/processed/negation_aware_data_large.txt
